export type Tour = "PPA" | "MLP" | "APP"
export type Gender = "M" | "F" | "Mixed"

export interface PlayerTour {
  code: "PPA" | "MLP" | "APP"
  appearances?: number
  earnings?: number
  active?: boolean
}

export interface Player {
  id: string
  slug: string
  name: string
  country?: string
  gender?: Gender
  dob?: string // Added date of birth field (YYYY-MM-DD format)
  bio?: string // Added bio field for player descriptions
  primaryTour?: Tour
  headshotUrl?: string
  sponsors?: string[]
  handedness?: "R" | "L"
  tours?: PlayerTour[]
  totals: {
    ytdPrize: number
    allTimePrize: number
    reportedContracts?: number
    endorsementsEstimate?: number
  }
}

export interface EventPayout {
  id: string
  eventSlug: string
  eventName: string
  tour: Tour
  date: string
  city?: string
  purse: number
  result: "Winner" | "Finalist" | "Semifinal" | "Quarter" | "Round"
  bracket: "MS" | "WS" | "MD" | "WD" | "XD"
  prize: number
  playerId: string
  sources: {
    title: string
    url: string
    date: string
    confidence: "confirmed" | "reported" | "estimated"
  }[]
}

export interface Event {
  id: string
  slug: string
  tour: Tour
  eventId: string
  eventName: string
  startDate: string
  endDate: string
  city: string
  stateCountry: string
  eventType: string
  prizePoolAmount?: number
  prizePoolStatus: "Reported" | "Unknown"
  sourceUrl: string
  notes?: string
}

export const mockPlayers: Player[] = [
  {
    id: "1",
    slug: "ben-johns",
    name: "Ben Johns",
    country: "US",
    gender: "M",
    dob: "1999-03-18",
    bio: "Ben Johns (born 1999) is an American professional pickleball player who has held the world number one ranking for much of the sport's modern era, amassing over 100 PPA Tour titles since 2016. He holds records for the most triple crowns in history and is well-known for his long-standing doubles partnership with his brother, Collin Johns. As the PPA Tour's most decorated male athlete, he has been central to defining the strategic evolution of the game.",
    primaryTour: "PPA",
    headshotUrl: "/ben-johns-pickleball.png",
    sponsors: ["JOOLA", "Vulcan"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 15, earnings: 75000, active: true },
      { code: "MLP", appearances: 8, earnings: 18750, active: true },
      { code: "APP", appearances: 3, earnings: 18750, active: true },
    ],
    totals: {
      ytdPrize: 125000,
      allTimePrize: 450000,
      reportedContracts: 500000,
      endorsementsEstimate: 200000,
    },
  },
  {
    id: "2",
    slug: "anna-leigh-waters",
    name: "Anna Leigh Waters",
    country: "US",
    gender: "F",
    dob: "2007-01-26",
    bio: "Anna Leigh Waters (born 2007) is an American pickleball player. She has been ranked #1 and is a multiple-time major champion. As of 2025, she is the second-highest earner in pro pickleball with over $5M in career earnings",
    primaryTour: "PPA",
    headshotUrl: "/anna-leigh-waters-pickleball.png",
    sponsors: ["HEAD", "Fila"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 12, earnings: 68000, active: true },
      { code: "MLP", appearances: 6, earnings: 17000, active: true },
    ],
    totals: {
      ytdPrize: 98000,
      allTimePrize: 320000,
      reportedContracts: 300000,
      endorsementsEstimate: 150000,
    },
  },
  {
    id: "3",
    slug: "jw-johnson",
    name: "JW Johnson",
    country: "US",
    gender: "M",
    primaryTour: "MLP",
    headshotUrl: "/jw-johnson-pickleball.png",
    sponsors: ["Franklin", "Adidas"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 5, earnings: 25000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 87500,
      allTimePrize: 285000,
      reportedContracts: 250000,
      endorsementsEstimate: 100000,
    },
  },
  {
    id: "4",
    slug: "catherine-parenteau",
    name: "Catherine Parenteau",
    country: "CA",
    gender: "F",
    primaryTour: "APP",
    headshotUrl: "/catherine-parenteau-pickleball.png",
    sponsors: ["Selkirk", "Lululemon"],
    handedness: "R",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 3, earnings: 15000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 76000,
      allTimePrize: 245000,
      reportedContracts: 200000,
      endorsementsEstimate: 80000,
    },
  },
  {
    id: "5",
    slug: "riley-newman",
    name: "Riley Newman",
    country: "US",
    gender: "M",
    primaryTour: "PPA",
    headshotUrl: "/riley-newman-pickleball.png",
    sponsors: ["Paddletek", "Nike"],
    handedness: "L",
    tours: [
      { code: "PPA", appearances: 8, earnings: 20000, active: true },
      { code: "MLP", appearances: 4, earnings: 10000, active: true },
      { code: "APP", appearances: 1, earnings: 5000, active: true },
    ],
    totals: {
      ytdPrize: 72000,
      allTimePrize: 220000,
      reportedContracts: 180000,
      endorsementsEstimate: 75000,
    },
  },
  {
    id: "6",
    slug: "meghan-dizon",
    name: "Meghan Dizon",
    country: "US",
    gender: "F",
    primaryTour: "MLP",
    headshotUrl: "/meghan-dizon-pickleball.png",
    sponsors: ["Engage", "Under Armour"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 65000,
      allTimePrize: 195000,
      reportedContracts: 150000,
      endorsementsEstimate: 60000,
    },
  },
  {
    id: "PKB-1201",
    slug: "tyson-mcguffin",
    name: "Tyson McGuffin",
    country: "US",
    gender: "M",
    primaryTour: "PPA",
    headshotUrl: "/tyson-mcguffin-pickleball.png",
    sponsors: ["Selkirk", "Nike"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 15, earnings: 75000, active: true },
      { code: "MLP", appearances: 8, earnings: 18750, active: true },
      { code: "APP", appearances: 3, earnings: 18750, active: true },
    ],
    totals: {
      ytdPrize: 68000,
      allTimePrize: 210000,
      reportedContracts: 175000,
      endorsementsEstimate: 85000,
    },
  },
  {
    id: "PKB-1202",
    slug: "simone-jardim",
    name: "Simone Jardim",
    country: "BR",
    gender: "F",
    primaryTour: "APP",
    headshotUrl: "/simone-jardim-pickleball.png",
    sponsors: ["HEAD", "Wilson"],
    handedness: "R",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 3, earnings: 15000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 58000,
      allTimePrize: 185000,
      reportedContracts: 140000,
      endorsementsEstimate: 70000,
    },
  },
  {
    id: "PKB-1203",
    slug: "collin-johns",
    name: "Collin Johns",
    country: "US",
    gender: "M",
    primaryTour: "MLP",
    headshotUrl: "/collin-johns-pickleball.png",
    sponsors: ["JOOLA", "Adidas"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 62000,
      allTimePrize: 195000,
      reportedContracts: 160000,
      endorsementsEstimate: 75000,
    },
  },
  {
    id: "PKB-1204",
    slug: "lucy-kovalova",
    name: "Lucy Kovalova",
    country: "CZ",
    gender: "F",
    primaryTour: "PPA",
    headshotUrl: "/lucy-kovalova-pickleball.png",
    sponsors: ["Paddletek", "Fila"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 10, earnings: 40000, active: true },
      { code: "MLP", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 55000,
      allTimePrize: 175000,
      reportedContracts: 130000,
      endorsementsEstimate: 65000,
    },
  },
  {
    id: "PKB-1205",
    slug: "zane-navratil",
    name: "Zane Navratil",
    country: "US",
    gender: "M",
    primaryTour: "APP",
    headshotUrl: "/zane-navratil-pickleball.png",
    sponsors: ["Franklin", "Under Armour"],
    handedness: "L",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 59000,
      allTimePrize: 180000,
      reportedContracts: 145000,
      endorsementsEstimate: 70000,
    },
  },
  {
    id: "PKB-1206",
    slug: "lea-jansen",
    name: "Lea Jansen",
    country: "US",
    gender: "F",
    primaryTour: "MLP",
    headshotUrl: "/lea-jansen-pickleball.png",
    sponsors: ["Engage", "Lululemon"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 52000,
      allTimePrize: 165000,
      reportedContracts: 125000,
      endorsementsEstimate: 60000,
    },
  },
  {
    id: "PKB-1207",
    slug: "parker-reed",
    name: "Parker Reed",
    country: "US",
    gender: "M",
    primaryTour: "PPA",
    headshotUrl: "/parker-reed-pickleball.png",
    sponsors: ["Vulcan", "Nike"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 10, earnings: 40000, active: true },
      { code: "MLP", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 38000,
      allTimePrize: 120000,
      reportedContracts: 90000,
      endorsementsEstimate: 45000,
    },
  },
  {
    id: "PKB-1208",
    slug: "jessie-irvine",
    name: "Jessie Irvine",
    country: "US",
    gender: "F",
    primaryTour: "APP",
    headshotUrl: "/jessie-irvine-pickleball.png",
    sponsors: ["HEAD", "Wilson"],
    handedness: "L",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 42000,
      allTimePrize: 135000,
      reportedContracts: 100000,
      endorsementsEstimate: 50000,
    },
  },
  {
    id: "PKB-1209",
    slug: "dylan-frazier",
    name: "Dylan Frazier",
    country: "US",
    gender: "M",
    primaryTour: "MLP",
    headshotUrl: "/dylan-frazier-pickleball.png",
    sponsors: ["Selkirk", "Adidas"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 45000,
      allTimePrize: 140000,
      reportedContracts: 105000,
      endorsementsEstimate: 52000,
    },
  },
  {
    id: "PKB-1210",
    slug: "callie-smith",
    name: "Callie Smith",
    country: "US",
    gender: "F",
    primaryTour: "PPA",
    headshotUrl: "/callie-smith-pickleball.png",
    sponsors: ["Franklin", "Fila"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 10, earnings: 40000, active: true },
      { code: "MLP", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 48000,
      allTimePrize: 150000,
      reportedContracts: 115000,
      endorsementsEstimate: 55000,
    },
  },
  {
    id: "PKB-1211",
    slug: "federico-staksrud",
    name: "Federico Staksrud",
    country: "AR",
    gender: "M",
    primaryTour: "APP",
    headshotUrl: "/federico-staksrud-pickleball.png",
    sponsors: ["JOOLA", "Under Armour"],
    handedness: "L",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 41000,
      allTimePrize: 130000,
      reportedContracts: 95000,
      endorsementsEstimate: 48000,
    },
  },
  {
    id: "PKB-1212",
    slug: "etta-wright",
    name: "Etta Wright",
    country: "US",
    gender: "F",
    primaryTour: "MLP",
    headshotUrl: "/etta-wright-pickleball.png",
    sponsors: ["Paddletek", "Lululemon"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 39000,
      allTimePrize: 125000,
      reportedContracts: 92000,
      endorsementsEstimate: 46000,
    },
  },
  {
    id: "PKB-1213",
    slug: "hayden-patriquin",
    name: "Hayden Patriquin",
    country: "CA",
    gender: "M",
    primaryTour: "PPA",
    headshotUrl: "/hayden-patriquin-pickleball.png",
    sponsors: ["Engage", "Nike"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 10, earnings: 40000, active: true },
      { code: "MLP", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 44000,
      allTimePrize: 138000,
      reportedContracts: 103000,
      endorsementsEstimate: 51000,
    },
  },
  {
    id: "PKB-1214",
    slug: "anna-bright",
    name: "Anna Bright",
    country: "US",
    gender: "F",
    primaryTour: "APP",
    headshotUrl: "/anna-bright-pickleball.png",
    sponsors: ["Vulcan", "Wilson"],
    handedness: "R",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 46000,
      allTimePrize: 145000,
      reportedContracts: 108000,
      endorsementsEstimate: 54000,
    },
  },
  {
    id: "PKB-1215",
    slug: "thomas-wilson",
    name: "Thomas Wilson",
    country: "US",
    gender: "M",
    primaryTour: "MLP",
    headshotUrl: "/thomas-wilson-pickleball.png",
    sponsors: ["HEAD", "Adidas"],
    handedness: "L",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 37000,
      allTimePrize: 118000,
      reportedContracts: 88000,
      endorsementsEstimate: 44000,
    },
  },
  {
    id: "PKB-1216",
    slug: "salome-devidze",
    name: "Salome Devidze",
    country: "GE",
    gender: "F",
    primaryTour: "PPA",
    headshotUrl: "/salome-devidze-pickleball.png",
    sponsors: ["Selkirk", "Fila"],
    handedness: "R",
    tours: [
      { code: "PPA", appearances: 10, earnings: 40000, active: true },
      { code: "MLP", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 43000,
      allTimePrize: 136000,
      reportedContracts: 101000,
      endorsementsEstimate: 50000,
    },
  },
  {
    id: "PKB-1217",
    slug: "jay-devilliers",
    name: "Jay Devilliers",
    country: "US",
    gender: "M",
    primaryTour: "APP",
    headshotUrl: "/jay-devilliers-pickleball.png",
    sponsors: ["Franklin", "Under Armour"],
    handedness: "R",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 40000,
      allTimePrize: 128000,
      reportedContracts: 96000,
      endorsementsEstimate: 48000,
    },
  },
  {
    id: "PKB-1218",
    slug: "jorja-johnson",
    name: "Jorja Johnson",
    country: "US",
    gender: "F",
    primaryTour: "MLP",
    headshotUrl: "/jorja-johnson-pickleball.png",
    sponsors: ["JOOLA", "Lululemon"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 36000,
      allTimePrize: 115000,
      reportedContracts: 85000,
      endorsementsEstimate: 42000,
    },
  },
  {
    id: "PKB-1219",
    slug: "matt-wright",
    name: "Matt Wright",
    country: "US",
    gender: "M",
    primaryTour: "PPA",
    headshotUrl: "/matt-wright-pickleball.png",
    sponsors: ["Paddletek", "Nike"],
    handedness: "L",
    tours: [
      { code: "PPA", appearances: 10, earnings: 40000, active: true },
      { code: "MLP", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 35000,
      allTimePrize: 112000,
      reportedContracts: 83000,
      endorsementsEstimate: 41000,
    },
  },
  {
    id: "PKB-1220",
    slug: "irina-tereschenko",
    name: "Irina Tereschenko",
    country: "RU",
    gender: "F",
    primaryTour: "APP",
    headshotUrl: "/irina-tereschenko-pickleball.png",
    sponsors: ["Engage", "Wilson"],
    handedness: "R",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 38000,
      allTimePrize: 122000,
      reportedContracts: 91000,
      endorsementsEstimate: 45000,
    },
  },
  {
    id: "PKB-1221",
    slug: "christian-alshon",
    name: "Christian Alshon",
    country: "US",
    gender: "M",
    primaryTour: "MLP",
    headshotUrl: "/christian-alshon-pickleball.png",
    sponsors: ["Vulcan", "Adidas"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 33000,
      allTimePrize: 105000,
      reportedContracts: 78000,
      endorsementsEstimate: 39000,
    },
  },
  {
    id: "PKB-1222",
    slug: "kate-fahey",
    name: "Kate Fahey",
    country: "US",
    gender: "F",
    primaryTour: "PPA",
    headshotUrl: "/kate-fahey-pickleball.png",
    sponsors: ["HEAD", "Fila"],
    handedness: "L",
    tours: [
      { code: "PPA", appearances: 10, earnings: 40000, active: true },
      { code: "MLP", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 34000,
      allTimePrize: 108000,
      reportedContracts: 80000,
      endorsementsEstimate: 40000,
    },
  },
  {
    id: "PKB-1223",
    slug: "andrei-daescu",
    name: "Andrei Daescu",
    country: "RO",
    gender: "M",
    primaryTour: "APP",
    headshotUrl: "/andrei-daescu-pickleball.png",
    sponsors: ["Selkirk", "Under Armour"],
    handedness: "R",
    tours: [
      { code: "APP", appearances: 10, earnings: 40000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "MLP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 32000,
      allTimePrize: 102000,
      reportedContracts: 76000,
      endorsementsEstimate: 38000,
    },
  },
  {
    id: "PKB-1224",
    slug: "lacy-schneemann",
    name: "Lacy Schneemann",
    country: "US",
    gender: "F",
    primaryTour: "MLP",
    headshotUrl: "/lacy-schneemann-pickleball.png",
    sponsors: ["Franklin", "Lululemon"],
    handedness: "R",
    tours: [
      { code: "MLP", appearances: 10, earnings: 50000, active: true },
      { code: "PPA", appearances: 4, earnings: 16000, active: true },
      { code: "APP", appearances: 2, earnings: 10000, active: true },
    ],
    totals: {
      ytdPrize: 31000,
      allTimePrize: 98000,
      reportedContracts: 73000,
      endorsementsEstimate: 36000,
    },
  },
]

export const mockPayouts: EventPayout[] = [
  {
    id: "1",
    eventSlug: "ppa-masters-2024",
    eventName: "PPA Masters 2024",
    tour: "PPA",
    date: "2024-03-15",
    city: "Indian Wells, CA",
    purse: 150000,
    result: "Winner",
    bracket: "MS",
    prize: 25000,
    playerId: "1",
    sources: [
      {
        title: "PPA Tour Official Results",
        url: "https://ppatour.com/results/masters-2024",
        date: "2024-03-15",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "2",
    eventSlug: "mlp-premier-level-2024",
    eventName: "MLP Premier Level 2024",
    tour: "MLP",
    date: "2024-04-20",
    city: "Columbus, OH",
    purse: 200000,
    result: "Winner",
    bracket: "WS",
    prize: 30000,
    playerId: "2",
    sources: [
      {
        title: "Major League Pickleball Results",
        url: "https://majorleaguepickleball.net/results/premier-2024",
        date: "2024-04-20",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "3",
    eventSlug: "app-tour-championship-2024",
    eventName: "APP Tour Championship 2024",
    tour: "APP",
    date: "2024-05-10",
    city: "Newport Beach, CA",
    purse: 125000,
    result: "Finalist",
    bracket: "MS",
    prize: 15000,
    playerId: "3",
    sources: [
      {
        title: "APP Tour Championship Report",
        url: "https://apptour.org/championship-2024-results",
        date: "2024-05-10",
        confidence: "reported",
      },
    ],
  },
  // Add more mock payouts...
]

export const mockEvents: Event[] = [
  // MLP Events
  {
    id: "MLP01",
    slug: "mlp-atlanta",
    tour: "MLP",
    eventId: "MLP01",
    eventName: "MLP Atlanta",
    startDate: "2024-05-09",
    endDate: "2024-05-12",
    city: "Atlanta",
    stateCountry: "GA, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP02",
    slug: "mlp-washington",
    tour: "MLP",
    eventId: "MLP02",
    eventName: "MLP Washington",
    startDate: "2024-06-13",
    endDate: "2024-06-16",
    city: "Washington",
    stateCountry: "DC, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP03",
    slug: "mlp-mid-season-tournament",
    tour: "MLP",
    eventId: "MLP03",
    eventName: "MLP Mid-Season Tournament",
    startDate: "2024-07-10",
    endDate: "2024-07-14",
    city: "Grand Rapids",
    stateCountry: "MI, USA",
    eventType: "Mid-Season Tournament",
    prizePoolAmount: 200000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP04",
    slug: "mlp-salt-lake-city",
    tour: "MLP",
    eventId: "MLP04",
    eventName: "MLP Salt Lake City",
    startDate: "2024-07-25",
    endDate: "2024-07-28",
    city: "Salt Lake City",
    stateCountry: "UT, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP05",
    slug: "mlp-kansas-city",
    tour: "MLP",
    eventId: "MLP05",
    eventName: "MLP Kansas City",
    startDate: "2024-08-03",
    endDate: "2024-08-05",
    city: "Kansas City",
    stateCountry: "MO, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP06",
    slug: "mlp-new-york",
    tour: "MLP",
    eventId: "MLP06",
    eventName: "MLP New York",
    startDate: "2024-09-19",
    endDate: "2024-09-22",
    city: "New York",
    stateCountry: "NY, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP07",
    slug: "mlp-virginia-beach",
    tour: "MLP",
    eventId: "MLP07",
    eventName: "MLP Virginia Beach",
    startDate: "2024-09-26",
    endDate: "2024-09-29",
    city: "Virginia Beach",
    stateCountry: "VA, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP08",
    slug: "mlp-las-vegas",
    tour: "MLP",
    eventId: "MLP08",
    eventName: "MLP Las Vegas",
    startDate: "2024-10-14",
    endDate: "2024-10-16",
    city: "Las Vegas",
    stateCountry: "NV, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP09",
    slug: "mlp-miami",
    tour: "MLP",
    eventId: "MLP09",
    eventName: "MLP Miami",
    startDate: "2024-10-24",
    endDate: "2024-10-27",
    city: "Miami",
    stateCountry: "FL, USA",
    eventType: "Regular Season",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP10",
    slug: "mlp-playoffs-round-1",
    tour: "MLP",
    eventId: "MLP10",
    eventName: "MLP Playoffs Round 1",
    startDate: "2024-11-01",
    endDate: "2024-11-03",
    city: "Dallas",
    stateCountry: "TX, USA",
    eventType: "Playoffs",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  {
    id: "MLP11",
    slug: "mlp-playoffs-round-2",
    tour: "MLP",
    eventId: "MLP11",
    eventName: "MLP Playoffs Round 2",
    startDate: "2024-11-22",
    endDate: "2024-11-24",
    city: "Orlando",
    stateCountry: "FL, USA",
    eventType: "Playoffs",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.majorleaguepickleball.co/news/mlp-by-margaritaville-announces-updated-2024-event-schedule/",
  },
  // PPA Events
  {
    id: "PPA01",
    slug: "hyundai-masters",
    tour: "PPA",
    eventId: "PPA01",
    eventName: "Hyundai Masters",
    startDate: "2024-01-10",
    endDate: "2024-01-14",
    city: "Mesa",
    stateCountry: "AZ, USA",
    eventType: "Cup",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/hyundai-masters-powered-by-msa/",
    notes: "Actual event",
  },
  {
    id: "PPA02",
    slug: "desert-ridge-open",
    tour: "PPA",
    eventId: "PPA02",
    eventName: "Desert Ridge Open",
    startDate: "2024-01-31",
    endDate: "2024-02-04",
    city: "Phoenix",
    stateCountry: "AZ, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/desert-ridge-open/",
  },
  {
    id: "PPA03",
    slug: "selkirk-red-rock-open",
    tour: "PPA",
    eventId: "PPA03",
    eventName: "Selkirk Red Rock Open",
    startDate: "2024-02-21",
    endDate: "2024-02-25",
    city: "St. George",
    stateCountry: "UT, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/selkirk-red-rock-open/",
  },
  {
    id: "PPA04",
    slug: "texas-open",
    tour: "PPA",
    eventId: "PPA04",
    eventName: "Texas Open",
    startDate: "2024-03-13",
    endDate: "2024-03-17",
    city: "Rockwall",
    stateCountry: "TX, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/cibc-texas-open-powered-by-tixr/",
  },
  {
    id: "PPA05",
    slug: "minnesota-open",
    tour: "PPA",
    eventId: "PPA05",
    eventName: "Minnesota Open",
    startDate: "2024-03-27",
    endDate: "2024-03-31",
    city: "Lakeville",
    stateCountry: "MN, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/minnesota-open-powered-by-progressive-insurance/",
  },
  {
    id: "PPA06",
    slug: "north-carolina-open",
    tour: "PPA",
    eventId: "PPA06",
    eventName: "North Carolina Open",
    startDate: "2024-04-03",
    endDate: "2024-04-07",
    city: "Cary",
    stateCountry: "NC, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/north-carolina-open-powered-by-the-james/",
  },
  {
    id: "PPA07",
    slug: "veolia-la-open",
    tour: "PPA",
    eventId: "PPA07",
    eventName: "Veolia LA Open",
    startDate: "2024-04-17",
    endDate: "2024-04-21",
    city: "Fountain Valley",
    stateCountry: "CA, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/veolia-la-open/",
  },
  {
    id: "PPA08",
    slug: "atlanta-open",
    tour: "PPA",
    eventId: "PPA08",
    eventName: "Atlanta Open",
    startDate: "2024-05-15",
    endDate: "2024-05-19",
    city: "Peachtree Corners",
    stateCountry: "GA, USA",
    eventType: "Slam",
    prizePoolAmount: 200000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/atlanta-open/",
    notes: "Moved from Cincinnati",
  },
  {
    id: "PPA09",
    slug: "sacramento-open",
    tour: "PPA",
    eventId: "PPA09",
    eventName: "Sacramento Open",
    startDate: "2024-06-05",
    endDate: "2024-06-09",
    city: "Roseville",
    stateCountry: "CA, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/sacramento-open/",
  },
  {
    id: "PPA10",
    slug: "orange-county-cup",
    tour: "PPA",
    eventId: "PPA10",
    eventName: "Orange County Cup",
    startDate: "2024-06-26",
    endDate: "2024-06-30",
    city: "San Clemente",
    stateCountry: "CA, USA",
    eventType: "Cup",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/orange-county-cup/",
  },
  {
    id: "PPA11",
    slug: "kansas-city-open",
    tour: "PPA",
    eventId: "PPA11",
    eventName: "Kansas City Open",
    startDate: "2024-08-07",
    endDate: "2024-08-11",
    city: "Overland Park",
    stateCountry: "KS, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/kansas-city-open/",
  },
  {
    id: "PPA12",
    slug: "tournament-of-champions",
    tour: "PPA",
    eventId: "PPA12",
    eventName: "Tournament of Champions",
    startDate: "2024-08-14",
    endDate: "2024-08-18",
    city: "Brigham City",
    stateCountry: "UT, USA",
    eventType: "Slam",
    prizePoolAmount: 200000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/tournament-of-champions/",
  },
  {
    id: "PPA13",
    slug: "jw-marriott-bonnet-creek-open",
    tour: "PPA",
    eventId: "PPA13",
    eventName: "JW Marriott Bonnet Creek Open",
    startDate: "2024-08-28",
    endDate: "2024-09-01",
    city: "Orlando",
    stateCountry: "FL, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/jw-marriott-bonnet-creek-open/",
    notes: "Relocated from Seattle",
  },
  {
    id: "PPA14",
    slug: "virginia-beach-cup",
    tour: "PPA",
    eventId: "PPA14",
    eventName: "Virginia Beach Cup",
    startDate: "2024-09-25",
    endDate: "2024-09-29",
    city: "Virginia Beach",
    stateCountry: "VA, USA",
    eventType: "Cup",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/stratusphere-gin-virginia-beach-cup/",
    notes: "Moved from March",
  },
  {
    id: "PPA15",
    slug: "las-vegas-cup",
    tour: "PPA",
    eventId: "PPA15",
    eventName: "Las Vegas Cup",
    startDate: "2024-10-09",
    endDate: "2024-10-13",
    city: "Las Vegas",
    stateCountry: "NV, USA",
    eventType: "Cup",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/las-vegas-cup/",
  },
  {
    id: "PPA16",
    slug: "oh-snap-daytona-beach-open",
    tour: "PPA",
    eventId: "PPA16",
    eventName: "OH SNAP Daytona Beach Open",
    startDate: "2024-10-23",
    endDate: "2024-10-27",
    city: "Holly Hill",
    stateCountry: "FL, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/oh-snap-daytona-beach-open/",
  },
  {
    id: "PPA17",
    slug: "milwaukee-open",
    tour: "PPA",
    eventId: "PPA17",
    eventName: "Milwaukee Open",
    startDate: "2024-11-14",
    endDate: "2024-11-17",
    city: "Milwaukee",
    stateCountry: "WI, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/milwaukee-open/",
  },
  {
    id: "PPA18",
    slug: "tour-finals",
    tour: "PPA",
    eventId: "PPA18",
    eventName: "Tour Finals",
    startDate: "2024-12-05",
    endDate: "2024-12-08",
    city: "San Clemente",
    stateCountry: "CA, USA",
    eventType: "Finals",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.ppatour.com/tournament/ppa-finals/",
  },
  // APP Events
  {
    id: "APP01",
    slug: "app-phoenix",
    tour: "APP",
    eventId: "APP01",
    eventName: "APP Phoenix",
    startDate: "2024-01-31",
    endDate: "2024-02-04",
    city: "Phoenix",
    stateCountry: "AZ, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-phoenix",
  },
  {
    id: "APP02",
    slug: "aarp-us-champions-cup",
    tour: "APP",
    eventId: "APP02",
    eventName: "AARP U.S. Champions Cup",
    startDate: "2024-02-01",
    endDate: "2024-02-04",
    city: "Daytona Beach",
    stateCountry: "FL, USA",
    eventType: "Signature",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.theapp.global/news/2024-aarp-champions-masters-release",
  },
  {
    id: "APP03",
    slug: "app-sacramento",
    tour: "APP",
    eventId: "APP03",
    eventName: "APP Sacramento",
    startDate: "2024-03-06",
    endDate: "2024-03-10",
    city: "Sacramento",
    stateCountry: "CA, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-sacramento",
  },
  {
    id: "APP04",
    slug: "app-austin",
    tour: "APP",
    eventId: "APP04",
    eventName: "APP Austin",
    startDate: "2024-03-13",
    endDate: "2024-03-17",
    city: "Austin",
    stateCountry: "TX, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-austin",
  },
  {
    id: "APP05",
    slug: "app-miami",
    tour: "APP",
    eventId: "APP05",
    eventName: "APP Miami",
    startDate: "2024-03-20",
    endDate: "2024-03-24",
    city: "Miami",
    stateCountry: "FL, USA",
    eventType: "Major",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-miami",
  },
  {
    id: "APP06",
    slug: "app-delray-beach",
    tour: "APP",
    eventId: "APP06",
    eventName: "APP Delray Beach",
    startDate: "2024-04-03",
    endDate: "2024-04-07",
    city: "Delray Beach",
    stateCountry: "FL, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-delray-beach",
  },
  {
    id: "APP07",
    slug: "app-houston",
    tour: "APP",
    eventId: "APP07",
    eventName: "APP Houston",
    startDate: "2024-04-10",
    endDate: "2024-04-14",
    city: "Houston",
    stateCountry: "TX, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-houston",
  },
  {
    id: "APP08",
    slug: "app-los-angeles",
    tour: "APP",
    eventId: "APP08",
    eventName: "APP Los Angeles",
    startDate: "2024-04-18",
    endDate: "2024-04-21",
    city: "Los Angeles",
    stateCountry: "CA, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-los-angeles",
  },
  {
    id: "APP09",
    slug: "app-st-george",
    tour: "APP",
    eventId: "APP09",
    eventName: "APP St. George",
    startDate: "2024-04-24",
    endDate: "2024-04-28",
    city: "St. George",
    stateCountry: "UT, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-st-george",
  },
  {
    id: "APP10",
    slug: "app-cincinnati",
    tour: "APP",
    eventId: "APP10",
    eventName: "APP Cincinnati",
    startDate: "2024-05-08",
    endDate: "2024-05-12",
    city: "Cincinnati",
    stateCountry: "OH, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-cincinnati",
  },
  {
    id: "APP11",
    slug: "app-new-york-city",
    tour: "APP",
    eventId: "APP11",
    eventName: "APP New York City",
    startDate: "2024-05-22",
    endDate: "2024-05-26",
    city: "New York",
    stateCountry: "NY, USA",
    eventType: "Major",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-new-york-city-major",
  },
  {
    id: "APP12",
    slug: "app-us-indoor-championships",
    tour: "APP",
    eventId: "APP12",
    eventName: "APP U.S. Indoor Championships",
    startDate: "2024-06-12",
    endDate: "2024-06-16",
    city: "TBA",
    stateCountry: "TBA",
    eventType: "Signature",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.theapp.global/news/app-announces-2024-event-calendar",
  },
  {
    id: "APP13",
    slug: "app-san-clemente",
    tour: "APP",
    eventId: "APP13",
    eventName: "APP San Clemente",
    startDate: "2024-06-25",
    endDate: "2024-06-30",
    city: "San Clemente",
    stateCountry: "CA, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-san-clemente",
  },
  {
    id: "APP14",
    slug: "app-southern-california",
    tour: "APP",
    eventId: "APP14",
    eventName: "APP Southern California",
    startDate: "2024-07-03",
    endDate: "2024-07-07",
    city: "Southern California",
    stateCountry: "CA, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/news/2024-aarp-champions-masters-release",
  },
  {
    id: "APP15",
    slug: "app-st-louis",
    tour: "APP",
    eventId: "APP15",
    eventName: "APP St. Louis",
    startDate: "2024-07-18",
    endDate: "2024-07-21",
    city: "St. Louis",
    stateCountry: "MO, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-st-louis",
  },
  {
    id: "APP16",
    slug: "app-womens-open",
    tour: "APP",
    eventId: "APP16",
    eventName: "APP Women's Open",
    startDate: "2024-07-24",
    endDate: "2024-07-28",
    city: "TBA",
    stateCountry: "TBA",
    eventType: "Signature",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.theapp.global/news/app-announces-2024-event-calendar",
  },
  {
    id: "APP17",
    slug: "app-chicago",
    tour: "APP",
    eventId: "APP17",
    eventName: "APP Chicago",
    startDate: "2024-08-28",
    endDate: "2024-09-01",
    city: "Chicago",
    stateCountry: "IL, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-chicago",
  },
  {
    id: "APP18",
    slug: "app-cincinnati-open",
    tour: "APP",
    eventId: "APP18",
    eventName: "APP Cincinnati",
    startDate: "2024-09-11",
    endDate: "2024-09-15",
    city: "Cincinnati",
    stateCountry: "OH, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-cincinnati-open",
  },
  {
    id: "APP19",
    slug: "app-fort-lauderdale",
    tour: "APP",
    eventId: "APP19",
    eventName: "APP Fort Lauderdale",
    startDate: "2024-10-02",
    endDate: "2024-10-06",
    city: "Fort Lauderdale",
    stateCountry: "FL, USA",
    eventType: "Major",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-fort-lauderdale",
  },
  {
    id: "APP20",
    slug: "app-dallas",
    tour: "APP",
    eventId: "APP20",
    eventName: "APP Dallas",
    startDate: "2024-10-09",
    endDate: "2024-10-13",
    city: "Rockwall",
    stateCountry: "TX, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-dallas",
  },
  {
    id: "APP21",
    slug: "app-southern-california-major",
    tour: "APP",
    eventId: "APP21",
    eventName: "APP Southern California",
    startDate: "2024-10-23",
    endDate: "2024-10-27",
    city: "Southern California",
    stateCountry: "CA, USA",
    eventType: "Major",
    prizePoolAmount: 150000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/news/app-announces-2024-event-calendar",
  },
  {
    id: "APP22",
    slug: "app-texas",
    tour: "APP",
    eventId: "APP22",
    eventName: "APP Texas",
    startDate: "2024-11-04",
    endDate: "2024-11-10",
    city: "TBA",
    stateCountry: "TX, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/news/app-announces-2024-event-calendar",
  },
  {
    id: "APP23",
    slug: "app-boca-raton",
    tour: "APP",
    eventId: "APP23",
    eventName: "APP Boca Raton",
    startDate: "2024-11-13",
    endDate: "2024-11-17",
    city: "Boca Raton",
    stateCountry: "FL, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/tour-schedule/app-tour-boca-raton",
  },
  {
    id: "APP24",
    slug: "app-dallas-atlantic-cup",
    tour: "APP",
    eventId: "APP24",
    eventName: "APP Dallas",
    startDate: "2024-11-22",
    endDate: "2024-11-24",
    city: "Dallas",
    stateCountry: "TX, USA",
    eventType: "Team Event",
    prizePoolStatus: "Unknown",
    sourceUrl: "https://www.theapp.global/news/app-announces-2024-event-calendar",
    notes: "Atlantic Cup",
  },
  {
    id: "APP25",
    slug: "app-fort-lauderdale-december",
    tour: "APP",
    eventId: "APP25",
    eventName: "APP Fort Lauderdale",
    startDate: "2024-12-11",
    endDate: "2024-12-15",
    city: "Fort Lauderdale",
    stateCountry: "FL, USA",
    eventType: "Open",
    prizePoolAmount: 100000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.theapp.global/news/app-announces-2024-event-calendar",
  },
  {
    id: "PPA19",
    slug: "ppa-spring-championship-2026",
    tour: "PPA",
    eventId: "PPA19",
    eventName: "PPA Spring Championship 2026",
    startDate: "2026-03-15",
    endDate: "2026-03-19",
    city: "Miami",
    stateCountry: "FL, USA",
    eventType: "Championship",
    prizePoolAmount: 250000,
    prizePoolStatus: "Reported",
    sourceUrl: "https://www.ppatour.com/tournament/spring-championship-2026",
    notes: "Future event for testing scheduled badge",
  },
]

export const events = mockEvents
